[files]
extend-exclude = [
  "src/lib/pow/wasm/*",
  "pnpm-lock.yaml",
  ".env.local",
  "src/routes/\\(app\\)/\\[username\\]/theme-editor/examplePage.md",
]

[default.extend-words]
ratatui = "ratatui"
additionals = "additionals"
datas = "datas"
